/*
 * @Author       : ee
 * @Date         : 2025-11-21 09:07:00
 * SVC reporting!
 */
#include <iostream>
using namespace std;

/**
 * @description  : swap
 * @param         {int&} a
 * @param         {int&} b
 * @return        {*}
 */
int swap(int &a, int &b) {
  int temp = a;
  a = b;
  b = temp;

  return 0;
}
class A {
  public:
    int x;
    A(int val) : x(val) {}
};

int swap2(int a, int b) {
  int temp = a;
  a = b;
  b = temp;
  return 0;
}
int main() {
  int j;
  for (int i = 1; i <= 8; i++) {
    j += i;
  }
  cout << "Hello, World!" << endl;
  cout << "中文测试" << endl;
  int a = 1, b = 2;
  swap2(a, b);
  cout << "a=" << a << ", b=" << b << endl;
  swap(a, b);
  cout << "a=" << a << ", b=" << b << endl;
  return 0;
}

/*
...............................................................................................................................................................................
...............................................................................................................................................................................
...............................................................................................................................................................................
.............................................................................:`,;''~~'';`:.....................................................................................
....................................................................`~>1lY&RW%NNNN@@NNN%WEKXl+~,`.............................................................................
..............................................................`!/I&$%@@NNW$ERKKKKKKKKKRREEWN@@NWK&Yl/!,.....................................................................
..........................................................'+IR%@@NWERK&FF&&&KKKKKKKKKKKKKKKKKKKKRRREW%NN%RY/'.................................................................
......................................................;/X$@@NWERREEEEEEEERKKKKKKKKKKKRREEEEEEEEEEERRKK&&KREWNNE*”:.............................................................
...................................................!lE@MNEREEERRKKKKKKKREERKKKKREEEERRKKKKKKKKKKRE$ERKKK&&KN@WI”...........................................................
................................................'l$@NWEEE$EK&&&&&KKKKKKKKKREEEEEERKKKKKKKKKKKKKKKKKKKR$ERKKKK&&ENMl;........................................................
.............................................:+K@NRE$EK&&&KKKKKKKKKKKKKKKKKKRKKKKKKKKKKKKKKKKKKKKKKKKKREERKKRKK&K$@@F”......................................................
...........................................,]W@WRE$RK&&&KKKKKKKKKKKKKKRRRKKKKKKKKKKRERKKKKKKKKKKKKKKKKKKKKR$RKKRRKK&RNMRi....................................................
.........................................,*N@R$EK&&KRRKKKKKKKKKKKKRE$WWEKKKKKKEWWWERKKKKKKKKKKKKKKKKKKKRERKRRRRKKK%ME>..................................................
........................................1NMEWK&&KRRKKKKKKKKKKKKRE$$$ERRRRKKKKKKRRREE$WRKKKKKKKKKKKKKKKKKKKR$RKRRRRRKK%M&!................................................
......................................'KM%WEKKKRRRRRRRRKKKKKKKREEERKKKKKKKKKKKKKKKKKKKRRE$EKKKKKKKKKKKKKRRKKKKRERRRRRRRKRNMX;..............................................
...................................../@M$EKKRRRRRRRRRRRKKKKKKEERKKKKKKKKKKKKKKKKKKKKRRRKKKKKEERKKKKKKKKRRRRRRRRKKREEKRRRRRKRM@}.............................................
....................................lM%RRKKRRRRRRRRRRRRRKKKKRERKKKKKRKKKKKKKKKKKKKKKKKKKKREEERRERKKRRRRRRRRRRRRRRRRKR$RRRRRRRRE%ME~...........................................
...................................XMWKKKRRRRRRRRRRRRRKKEW%NN%%WERKKRKKKRKKKKKKKKKKEW%N@@@@@@NNWEKKRRRRRRRRRRRRRRRKKWRRRRRRKREE@M/..........................................
.................................`KMEKRRRRRRRRRRRRRRKRWN@@@@@@@@@@@N%EKRRRKKKKRRKKKN@@@@NNNNNN@@@@NKKRRRRRRRRRRRRRRRKRWERRRRRKRE%MY:........................................
................................i%@KKRRRRRRRRRRRRRKKW@@NNNNNNNNNNNNN@M%KKKRRRRRKKRN@@NNNNNNNNNNNNNNNMNEKRRRRRRRRRRRRRRRRRWEKRRRRKREWMR`.......................................
..............................:YMWKKRRRRRRRKKKRRRRRN@NNNNNNNNNNNNNNNNNM%WN@@@@NNWN@NNNNNNNNNNNNNNNNNNMMERRRRRRRRRRRRRRRRRRWKRRRRKRW$M$;......................................
.............................~MRKRRKKKKKKKKKKRRRKN@NNNN%%%%%%%%%NNNNN%@M@@@@@MMM@NNNNNNNN%%%%%%NNNNN%M@KRRRRRRRRRRRRRRRRRKWEKRRRRKEW$M%;.....................................
............................i@@KKRKKKKKKKKKKKKKRKMNNN%%%%%%%%%%%%%%%N%@@%%WWW%N@NNNN%%%%%%%%%%%%%%%%%NMKRRRRRRRRRRRRRRRRRR%EKRRKKR$$EM$`....................................
...........................iM%KKKKKKKKKKKKKKKKKKK%MNN%%%%%WWWWW%%%%%%%%@NERRRRRRNM%%%%%WWWW%%W%%%%%%N%NMEKRRRRRRRRRRRRRRRRRKRWRRRKKKE$$$MK....................................
..........................>M%KRRRRKKKKKKKKKKKKKKKEMN%%%WWWWWWWW$$$WWWNMEKKKKKKKRMNW%%WWWWWWWWWWWWWWWW@MEKRRRRRRRRRRRRRRRRRRKEKRKKKR$$$$M*...................................
.........................'M@KREERKKKKKKKKKKKKKKKK&WM%WWWWWW$$EEEEEEENME&KKKKKKK&EMNWWWWWWWWWWEEEEE%M%WEKRRRRRRRRRRRRRRRRRRKRKRRRKR$$$E%M!..................................
.........................KMRREK&KKKKKKKKKKKKK&RKK&WMNW$$$$ERRRRREW@%K&KKKKKKKKK&RN@%$$$$$$EEEEEEW@M%$WEKRRRRKKRKKRRRRRRRRRRRRRRKKW$$$E@W`.................................
........................!MWERF&KKKKKKKKKKKKKKKWKKKKFRWN@N%WE$W%NN%E&KKKKKKKKKKKK&KN@@N%WWEEEW%@MN$$$$WRRRKKKKKKKKKKKKKKKKRRRRKRKR%$$$$MY.................................
......................:.IM$&XKKKKKKKKKKKKKKK&WR&KK&&&XIFRWWWWWEKXI*YXFFFF&&&&&&&FFFYII&EW%%NNNN%%WW$$$$$$KKKKKKKKKKKEKKKKKKKKKKKRKKRW$$ENM;................................
.......................”@@FFKKKKKKK&K&&KKKK&RW&K&&&&&KXllll***llll********************lllllXKKKKKKK%W$$$$$WRKKKKKKKKKREKKKKKKKKKKKKKKKR%$$$MY................................
......................iMNXFKKKKKKKKKKKKK&KK&WR&&&&&&&&KFI*&X*IIII*****I*************I*FXIIXKKKKKKKR%W$$$$$$$KKKKKKKKKREKKKKKKKKKKKKKKKKR%$$NM;...............................
.....................}MY&KKKK&&&&&&&KKKKK&RW&&&&&&&&&&&FIRI*I************************RYIFK&&KKKKKR%EEE$$ERKKKKKKKKREKKKKKKKKKKRKKKKKKR%WWM*...............................
....................*MRI&KKKK&&&&&&&&&&&&&&E$&&&&&&&&&&&&KEI*************************IKX&K&&&&&&K&E@EEEEEEE$KKKKKKKKREKKKKKKKKKKEKKKKKKKWWM$...............................
...................YM&IFKKK&&&&&&&&&&&&&&&&WR&&&&&&&&&&&FR$&FY********************l**KE&&&&&&&&&K&%MWEEEEEEERKKKKKKKREKKKKKKKKKKKWRKKKKKKKWN@,..............................
..................XMFIXKKK&&&&&&&&&&&&&&&&&WK&&&&&&&&&&&FR$&&&FXYI***************IYF&KF&&&&&&&&&RMRNEEEEEEEEE&KKKKK&EEKKKKKKKKKK&E$&KKKKKKKR%M”.:............................
.................&MFIY&KK&$$&&&&&&&&&&&&&FKW&&&&&&&&&&&&FK$&&FF&&FFXXYYIIIIIIYYXF&&FKF&&&&&&&&&FN@”RNREEEEER$$&&KKKK&RKKKKKKKKKKKKWKKKKKKKKKKN&..............................
................&MFIXXK&&%MRF&&&&&&&&&&&&FRWF&&&&&&&F&&&&&$&FFFFFFFFFFFFFFFFFFFFFFFXERFFFFFF&&&FRMl'+MREEEER$$&&&&&&&K&KK&&KKKKKK&RKKKKKKKKKFWE'............................
...............XMFIXY&&R@MRF&&&&&&&&&&&&&FEF&FFFFFFFFFFFFR&&&FFFXXXXXXXXXXXXXFFFX&W&F&KKKKKKKF@@l}iIMEREEER$$&&&&&&R$&&&&&&&&&&KK&RKKKKKKKKKKFE@>...........................
..............*M&IXYXFMMF&&&&F&&&&&FFF&FEFFFFFFFFFF&KFKM%FK&&FXXXXXXXXXXXXXXXFFXE$&F&&FFFFFX%@/1lI*MERERR$$&&&&&&ER&&&&&&&&&&KK&RWKKKKKKKKKKRXKM1..........................
.............iMEIXXXY%@@M&&&&&&FR&FFFFFF&FRFFFFFFF&KK&&XWN@&XXXXXXXXXXXXXXXXXXXXX&NFFXXXFFFYEM}'~~~~~IMEKERWEF&&&&&$&&&&&&&&&&&KKFKNKKKKKKKKKKRX&M}.........................
............,N%IXXXY%%1@X&&&&F&EFFFFFFFFF&%&FFFF&&&FXXXX@&F@YXXXXXXXXYXYYXXXXXXXYWMWXXXXXXXYRM*'!!”””!'lMKRWR&&&&FEEF&&&&&&&&&&&&FK%%WR&KKKKKKKKRY&M1........................
............&MXYXXIW@,XM&F&&&&F&EFFFFFFFFFXEXFFFFXXXXXXXMF!NIXXXXXYYYYYYYYXYYXYKNE%YXXXXXIRMl'!!”~`,!”'1NNRW&FFFF&$&F&&&&&&&&&K&FXK%W%KKKKKKKKKKIRM>.......................
...........~MEIXXIRM”`M%X&FFFFFKFFFFFFFFFXR@EYFXXXFXXXXXMF'1MRIXYYYXXYYYYYYYYYYYMIXNYXXXYYWM]'””~,...:'”!iKNFFFFFEEFFFFFF&&&FR%FFXK%$$WWEKKKKKKKKF*WN,......................
...........}MFYXY&M}.1MRF&FFFFFKW&FFFFFFFFX&@MRYXXXYXXXXY@&!~}MRIYYYXNFIYYYYYYY*$%~&%YXYIF@W+~”~,:.::`:`'~!”@EXFFXRFFFFFFFF&&F%%FFXRN$$EWR&&KK&K&YYMK......................
...........*MXXXY@R..XMFFFFFFFFKWRXFFFFFFFFX%N@EYYKRYYXXYNW!”~/@IYYI$@YYYYYYYI&M/'R%IIXWMY~';`:::``````:..*MXFFXKW&XFFFFFFF&FRN%&FXW%W$$EM@F&&&&YI&M/.....................
...........1M&YYKM>..KMXFFFFFFFKW%&&K&FXXYYIK%]%%XYNNKFYIRMi~”~>WNXIYXM%YIYYYIIMI!~EEIK%Ki~~';:::::..:`~il]WRXFXKW&XXXFFFFFFF&N$%KF&NRW$EM%>R@KFK&YYINW:....................
...........;M%YYWM,..MXFFFF&K&KKKl11111}]]}}l>`XNEX%MREKMK!”~~~YWKY*EM@XIYY*NR!'~MN@MF”~~';;`,;'”/*F$%@@M%XXXKW&YXXXXXFFFF&%WENKF$%EEEEW$%%”..}NF&XYI&M!....................
............*MKIN@`..$@YXFK&I}//]*YXFXYI***IYYW&:iX%E@K+lIXX!~'!i}MNRXWFNRI*%W!,.'Fl*WMMMN%WWW%NMMMM@NW%@RKFRW&YXXXXXXFFX&%WRW%FRNEREEEEM$:....;KNFYYYYM1....................
.............FMFR@`..EMYXF}+]YFFI}+”~''~~~!!~'”@K:X%%%%ERK&FKEW@MMW/+KMX>RWNE':.:....`iIR%@MMMM@%%%NM@WNMR&EW$&YXXXXXXXFXKNWRENERNRREEEREM+...:..F@YYYIM*....................
..............l@WM/..&MFl”IF]i~'~!i+++i>”””””~>Ml>@NNNM@@@MMMM%Xi:...'+i..”/:.:::::::...:;”/lX&EMMMR]”*NER%%EFYXXXXXXXYFE%RRW%$%RRREEEERMF.......KWIXY@]....................
...............;*$&..lMK”+M+.;''';!”!!!!!!”””””'lM!]YFEEN@MFli;..:`::...:....::::::::::`:::....`/XF;:IMN$MRFYXXXXXXYXKWWRKRR$ERKERREEERM+.::,~iYEXYXM”....................
..................:..'M%'/M”`,,`,!>””””!”””””””!'W$.`,;`*W],:::`,,`:::::::,`:::::::::::::```,,,,`:::`;11!iWEYYXXXXYYXKW%RKRRRRRRR&XEEREEER@MEKKRE$EFKXXM&.....................
......................XM>”Mi`;`,~~~~!!””””!~~~!”!/M}:,`,,,:`,,,```::::::::'`::::...:::::::``````,,,,,,:.>NEYYYYYYX&E%%RWEKRRRRRKFFXRREER%MR&&&FXXYXFKW]......................
......................,NR;M].`”]*YYl1i!~''!/*X&RRK%@;l/;,,,,`````::::::::.......:~'.:::::::``````,,,,`;*N&IYXF&RW$%WKF$%KRRRRKXXFXRRERWMW&KKKREWRX/`.......................
.......................!%!N&>RN@@NNNN%EF]lKEERRKKRWM]/N!`,````::::::::::.'”!~!>i+i;.:::::::::``````,,,X@EEE$$$E&&E$&&&K%RKRR&XXFFXRRR%M$&&&&FY*}i':..........................
........................~'FM%N%WWWWWWW%NN@%WWWW%%%@N`.:`,```:::::::::::.,~~~';`...:::::::::::``````:./%%R&FXYYI&WE&&&&&WRKFXFFFFXERE@@E,.....................................
............`',`:.........+M%W%%%%WWWWWWWWWW%%%%%%W%M!~;....:::`:::::::::.......:::::::::::`:::....`”F%&IYYYYYXEWKF&&&FK@WFFXFFFFFFE%M$&R'.....................................
...........`1]]]}1//++>...:N@W%%%%%%WWW%W%WWWWW%%%W%M>FNKI/~,.........:::::::::::::::.........,!+lF%MEYYXXXYXRWE&&&&F&%MMEXFFFFFFXRMY*YW/.....................................
...........~]>,'~>}}}li....IM$%%%%%%%%WWWW%%%%%%%%WNM~KWN@NWRF*}+”~;,`.:..........:`,;'!i}*FEWNN@MWXYXXXYYKWWKF&F&R%@&i@RXFFFFFXXMWl*I*&&.....................................
...........~li...']}1!.....,N@$%%%%%%%%%%%%%%%%%%WNM1,%@RREW%%N@M@NWWW&RK*****FR&&&FFMNN@@M%WN%&YXXXYY&WRFF&KWEI~.1MXXFFFFXX@N**II*Y$'....................................
...........;]1`..,!;:.......”@@W%%%%%%%%%%%%%%%%WNi..`l$%N%$W%N%%%%@@I”/EE*]IX&l>”!!,'WNWW%NM@RYXFXYY&$RKKEE$$%'~1%EXFFFFY&@WI*III*YW>....................................
............i]i..............~$@%%W%%%%%%WW%%%%NNMX......,~+XM@@N%%@%El;~iXM@NME!`~!';”&@@MMMMYYFFYXRNN%@%RRK&XI*YREERXFFXYFW@Kl*IIII*YWi....................................
.......:”+/>+}]”...,!>>”'::,,..1@@@NNN%%%@@@@N@MWMY`lFKX'1$@NNN%N@MWY*>YWM@MM@MN];'>YNMN@MM%FIYXXFE@W>:,/WY**IYYYIIYFXFXXF$@IlIIIIII*XW!....................................
......`}l]]]}}1]'.~+!,,!+ii>;.+%R&REW%%NN%ERKKKWW$@R;}>~MMMNNNNNMMMMIY]>`'!>>”!'l1YMMM@@MMRIYXYF$@WME>..`]EWRXYIYXFFXX&$%MYl*IIIIIII*KE`....................................
......;*]}11}}}l!.``....:``...iNWWWEKERK&KKKKRR%N%!`;~,YRMNNNNM@KFIRXX&FFFFFXI*K@%FKEM@FIYIXE@MMMEYM]...:>IREEEEW%IREl*IIIIIIIIIIW*.....................................
.......!}}]]]}/~...............`!i/]&ME&KKKKKKKKM”,>>>”F%M@@@NM@@*>*MMMMMMMMMMMMM@M&”>&MXYYIK@MMM@E&R&KM;.:....'>1*Yl/~.iKIIIIIIIIIII*&W'.....................................
........:`;,,`......................`M@K&KKKKKKK&MY:,`::.`%MMMMM%%RWERFE%FWNRE$%NMMKEM&YYX%MMM@KFWMMMY@l..............}EI*IIIII*III*YW1......................................
...................................:.”X$%R&&K&KK&MF.......XFXM@>,`.;:.`.;&/R':,.:`;~”+NWYYF@M@@MNMK}WF%K.............lEI*IIII**FFI*IWl.......................................
......................................i1}E%WREE@W'......;K!.X&.......:,.}R~`,.......:@RYFM@NNNN@MMl,IM%MR............*EIIIII**XKEI*YW*........................................
....................................'E~.:!&MK%W>:.......I]..*]:,:......,::`:.....:`:1MIWMNNNN@NMMM%EM@MN'..........lI*II**F&FYlFW1.........................................
...................................'@].....:@1+M:......,Il:`./K..,,,`...:,:.::....::.RMME%M%%NMK+i]&NMM@@M$`........+WI*I**XRY+FYIEK”..........................................
...................................~W*>;:.`.&W`R$;:.../F}.:`:.XK!....~”;.;.`.;}]}}/!+M%%@@M@MM%WWK]!!YM@M@Ml.......;F*I*YEX!~FFKR}:...........................................
....................................`]FKRF}~%K:,I&K&I1+;:......>&F`~Y]}IYY>;iK1~~>/l&%@@@N@RI&WNNN@%I”NMMNW%;......]WII*KE+:1R&}`.............................................
.........................................;I%I`::...'/FNF`.....:.iW+W>...;+*XE'.:::...:!1XRl!..,+F%NWN%M@M%NX......IE**EF,.~F}!:...............................................
........................................”EY`..`;”+}lIYK]:.....:.*NNl.:.`...i/;`:..........;>>,...~YN%NM@M$$$@”...../WIEY.......................................................
.......................................”M$}IFFFXI]/>~,.........!NW@X..:,``,”'”+:............:,:....!&MNM%EENX.....:l$&:.......................................................
.......................................:”//i”;,+l/'..........:]@%W$/..``..`'~'>}.................::.IM@%$$$$N'......'`........................................................
...............................................`!}FR&]”;``;>lM%EM/...::...!!~;/!.............:::..IM%%E$$$EN*................................................................
...................................................,”XM@W$%@NW%EE@F.```;`..'i;'+!................'FMWYFWWEEEEW$:...............................................................
.....................................................FMWEERKKRWEEEM+.:..`~!;”+/i:::::........:~}FEW%FF&YKWEEEN”...............................................................
....................................................~M%EREE$%NM@%N@@]::;>>'!F>..........,!/*X&Fl>:&@WFY&YI&$$MI...............................................................
....................................................iMMNN%KY}!>}}''F&$];,+WXIi””>/lYF&&F*1!`....”I&EKWWK$KY”...............................................................
....................................................:i1i!;:..........`!EKFi.`+]***l1i~,.............:;~'~~;`..................................................................
.......................................................................:>i:....................................................................................................
...............................................................................................................................................................................
...............................................................................................................................................................................
...............................................................................................................................................................................
*/